### ISSUE TITLE
Contrib alpine-pihole

### ISSUE THREAD

**Issue by SamTV12345** [r10513/pihole_alpine#3]
I saw that you forked the project. If you want to you can create a pull request. At some point it didn't really work and I gave up.

**Comment by r10513** [comment]
Hi there! I created a pull request. Thanks for your work! :)

Il giorno dom 28 mag 2023 alle ore 17:54 SamTV12345 <
***@***.***> ha scritto:

**Comment by SamTV12345** [comment]
You're welcome. Good luck with the update.

**Comment by r10513** [comment]
SamTV12345 should review my contribution, and either accept, or reject 🙂
